language: php

dist: trusty
sudo: false

git:
    depth: 50

branches:
    only:
        - master
        - /^\d+\.\d+$/

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: SYMFONY_VERSION=4.1.* TEST_COVERAGE=true
        - php: 7.3
          env: SYMFONY_VERSION=4.2.*
        - php: 7.3
          env: SYMFONY_VERSION=4.3.*
        - php: 7.3
          env: SYMFONY_VERSION=4.4.*
        - php: 7.4snapshot
          env: SYMFONY_VERSION=5.0.*
        - php: nightly
          env: COMPOSER_UPDATE_FLAGS=--ignore-platform-reqs
    allow_failures:
        - php: nightly
cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.php_cs.cache

before_install:
    - if [ "${DEPENDENCIES}" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [[ "${TEST_COVERAGE}" != "true" ]]; then phpenv config-rm xdebug.ini || true; fi
    - composer selfupdate
    - if [ "${SYMFONY_VERSION}" != "" ]; then perl -pi -e 's#"(symfony/.*)":\s*".*"#"$1":"'"${SYMFONY_VERSION}"'"#' composer.json; fi;
    # disable default memory limit
    - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo memory_limit = -1 >> $INI

install: travis_retry composer update --prefer-source --no-interaction --optimize-autoloader ${COMPOSER_UPDATE_FLAGS}

script:
    - bin/phpunit --debug $( if [ "$TEST_COVERAGE" = "true" ]; then echo "-d xdebug.max_nesting_level=1000 --coverage-clover=build/logs/clover.xml"; fi; )
    - if [ "${PHP_CS_FIXER}" = "true" ]; then composer require "friendsofphp/php-cs-fixer:^2.0" && bin/php-cs-fixer fix --diff --dry-run -v; fi;

after_script:
    - if [ "${TEST_COVERAGE}" = "true" ]; then composer require "satooshi/php-coveralls:^1.0" && travis_retry php bin/coveralls -v; fi
